jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - checkout
      - run: "echo \"ğŸ”§ Building the application...\""

  test:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - run: "echo \"ğŸ§ª Running tests...\""

  deploy:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - run: "echo \"ğŸš€ Deploying the application...\""

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:            # ğŸ‘ˆ æ‰‹å‹•æ‰¿èªã‚¸ãƒ§ãƒ–
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
